.catalog:
  name: "Gitlab Runner"
  version: "v1.8.0"
  description: "Gitlab CI runner."
  minimum_rancher_version: v0.44.0
  questions:
    - variable: "GITLAB_SERVER_URL"
      label: "Gitlab server url"
      description: "The public url for gitlab ci (e.g. : gitlab.mycompany.com/ci)"
      type: "string"
      required: true
    - variable: "RUNNER_DESCRIPTION"
      label: "Runner Description"
      description: "The name of the runner"
      type: "string"
      required: true
      default: "rancher-runner"
    - variable: "RUNNER_TOKEN"
      label: "Runner token"
      description: "The gitlab token to register the runner"
      type: "string"
      required: true
    - variable: "RUNNER_EXECUTOR"
      label: "Runner executor (docker, shell)"
      description: "The runner executor (docker, shell)"
      type: "string"
      required: true
      default: "docker"
    - variable: "RUNNER_DOCKER_IMAGE"
      label: "Runner Docker Image"
      description: "Image to start when using 'docker' executor."
      type: "string"
      required: true
      default: "docker:latest"
    - variable: "RUNNER_DOCKER_MODE"
      label: "Docker mode"
      description: "Docker mode to use : 'socket' to share the host docker socket and use the host deamon, 'dind' to use docker in docker"
      type: "string"
      required: true
      default: "socket"
    - variable: "RUNNER_DOCKER_PRIVATE_REGISTRY_URL"
      label: "Private registry url"
      description: "If you want to pull and push image to/from a private registry, fill the private registry host + port (e.g. : my-repo.company.com:5000)"
      type: "string"
      required: false
      default: ""
    - variable: "RUNNER_DOCKER_PRIVATE_REGISTRY_TOKEN"
      label: "Private registry token"
      description: "If you want to pull and push image to/from a private registry, fill the private token. To get a private token, use docker login on a linux, then get the token in ~/.docker/config.json"
      type: "string"
      required: false
      default: ""
