graylog:
  image: graylog2/server:2.1.2-1
  environment:
    GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
    GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
    GRAYLOG_WEB_ENDPOINT_URI: ${GRAYLOG_WEB_ENDPOINT_URI}
    GRAYLOG_ELASTICSEARCH_CLUSTER_NAME: ${GRAYLOG_ELASTICSEARCH_CLUSTER_NAME}
    GRAYLOG_MONGODB_URI: ${MONGO_URI}
    GRAYLOG_ELASTICSEARCH_DISCOVERY_ZEN_PING_UNICAST_HOSTS: ${ELASTIC_URI}
  ports:
    - 12201:12201/tcp
    - 12201:12201/udp
    - 80:9000
